### ISSUE TITLE
Test: add unit tests

### ISSUE THREAD

**Issue by cybardev** [cybardev/resumake#3]
- [ ] make tests directory
- [ ] make unit_tests subdirectory
  - [ ] create test script for each component
  - [ ] create test script for util functions
  - [ ] create test script for builder module
- [ ] add workflow to run unit test scripts
  - [ ] call workflow in other workflows and only run main jobs if tests pass

**Comment by analytical-aakriti** [comment]
hey, do you want to delegate some work?

**Comment by cybardev** [comment]
@analytical-aakriti Apologies for the late response. Sure, I'd love some help with implementing the unit tests. Feel free to fork the repo and make a PR against the [`3-test-add-unit-tests`](https://github.com/cybardev/resumake/tree/3-test-add-unit-tests) dev branch.

Have you seen the internals of the project?
- If so, you can get started on the tests for the functions in [`utils.py`](https://github.com/cybardev/resumake/blob/main/src/resumake/utils.py), or let me know what you'd like to work on
- If not, you might want to have a look around in the [`src/resumake`](https://github.com/cybardev/resumake/tree/main/src/resumake) directory

Let me know if you have any questions. Thanks.

**Comment by cybardev** [comment]
Closing as the structure of the project has changed significantly. Will re-evaluate test requirements and open new issue if needed.
